name: Build and test

on:
  push:
  pull_request:

env:
  working_directory: third_party/pytorch/third_party/nvfuser

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        working-directory: ${{ env.working_directory }}
        run: flake8
