name: Lint

on:
  push:
  pull_request:

env:
  working_directory: third_party/pytorch/third_party/nvfuser

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        working-directory: ${{ env.working_directory }}
        run: flake8

  yapf (formatting suggestion):
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install yapf
        run: pip install yapf
      - name: Run yapf
        working-directory: ${{ env.working_directory }}
        # do not add --exit-code here since this job is only a suggestion that does not fail
        run: |
          yapf -ri .
          git --no-pager diff

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install clang-format
        run: pip install clang-format
      - name: Run clang-format
        working-directory: ${{ env.working_directory }}
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cu\|c\|h\)' -exec clang-format -style=file -i {} \;
          git --no-pager diff --exit-code
