name: Lint

on:
  push:
  pull_request:

jobs:
  yapf:
    runs-on: ubuntu-latest
    steps:
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install yapf
        run: pip install yapf
      - name: Run flake8
        run: yapf --style=.yapf.cfg -rd .
