name: pull

on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: localhost:5005/a_private_local_image
    steps:
      - name: build
        run: |
          echo "repository ${{ github.repository }}"
          echo "sha ${{ github.sha }}"
  
  # WIP!
  test:
    runs-on: self-hosted
    container:
      image: somethingaaaaa
    steps:
      - name: test
        run: |
          echo "run some test"
