name: pull

on:
  pull_request:
  push:
   branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    container:
      image: localhost:5005/a_private_local_image
    if: >
      contains([xwang233], github.actor) &&
      startsWith(github.event.comment.body, '!build')
    steps:
      - name: build
        run: |
          echo "run some build"
          echo "repository ${{ github.repository }}"
          echo "sha ${{ github.sha }}"

  # WIP!
  test:
    needs: build
    runs-on: self-hosted
    container:
      image: localhost:5005/a_private_local_image
    steps:
      - name: test
        run: |
          echo "run some test"
          echo "repository ${{ github.repository }}"
          echo "sha ${{ github.sha }}"
