name: self hosted 2

on:
  push:
  pull_request:

env:
  working_directory: third_party/pytorch/third_party/nvfuser

jobs:
  run_test:
    runs-on: self-hosted
    container:
      image: localhost:5005/a_private_local_image
    steps:
      - name: start job
        run: echo "${{ github }}"
